/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginscreen;
import javax.swing.ImageIcon;
import mainscreen.mainScreen;
import util.koneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author muhar
 */
public class login extends javax.swing.JFrame {
    private Connection cn;
    private Statement st;
    private ResultSet rs;
    
    public login() {
        initComponents();
        login_button.setOpaque(false);
        login_button.setContentAreaFilled(false);
        login_button.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password_field = new javax.swing.JPasswordField();
        toogle_show_password = new javax.swing.JCheckBox();
        login_button = new javax.swing.JButton();
        username_field = new javax.swing.JTextField();
        login_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nobu");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password_field.setAlignmentX(0.0F);
        password_field.setAlignmentY(0.0F);
        password_field.setBorder(null);
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 30));

        toogle_show_password.setText("Show Password");
        toogle_show_password.setBorder(null);
        toogle_show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogle_show_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(toogle_show_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginscreen/Login Button.png"))); // NOI18N
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 160, 60));

        username_field.setBackground(new java.awt.Color(255, 255, 255));
        username_field.setForeground(new java.awt.Color(0, 0, 0));
        username_field.setBorder(null);
        username_field.setCaretColor(new java.awt.Color(0, 0, 0));
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 240, 30));

        login_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginscreen/Login Screen.png"))); // NOI18N
        getContentPane().add(login_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        
        // Membuat Constructor Koneksi agar getKoneksi() dapat dipanggil
        koneksi Koneksi = new koneksi();
        // Query untuk mengambil database
        String sql = "SELECT * FROM user_info";
        
        try {
            // Untuk mengambil database
            cn = Koneksi.getKoneksi();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            
            // Cek keseluruhan isi dari user_info
            while(rs.next()){
                String username = rs.getString("username");
                String password = rs.getString("password");
                
                // Mencocokan username dan password dengan setiap username dan password yang ada di database
                if(username_field.getText().contains(username) && password_field.getText().contains(password)){
                    JOptionPane.showMessageDialog(null, "Berhasil Login");
                    new mainScreen().show();
                    this.dispose();
                    break;
                } else {
                    // Munculkan JOptionPane ini apabila tidak ada data yang cocok
                    JOptionPane.showMessageDialog(null, "Username atau Password salah");
                }
            }
            
        } catch (Exception e) {
            // Apabila terjadi error ex: username tidak ditemukan atau database tidak terkoneksi
            System.out.println("Error mengambil username karena " + e.getMessage());
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/mainscreen/miku.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void toogle_show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogle_show_passwordActionPerformed
        // TODO add your handling code here:
        // Tombol untuk mengubah seluruh String menjadi char bentuk "*"
        if(toogle_show_password.isSelected()){
            password_field.setEchoChar((char)0);
        } else {
            password_field.setEchoChar('*');
        }
    }//GEN-LAST:event_toogle_show_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel login_background;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JCheckBox toogle_show_password;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
