/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainscreen;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.koneksi;

/**
 *
 * @author muhar
 */
public class mainScreen extends javax.swing.JFrame {
    
    private Statement st;
    private Connection cn;
    private ResultSet rs;
    
    String[] paid_text_set = {
        "What did you buy?",
        "Can you spare more money?",
        "I think that is too much for you to spend.",
        "If you have money to spend, would you give me a little?",
        "Buy something else? I told you many times to save your expenses"
    };
    
    String[] income_text_set = {
        "Well done, you saved yourself by raising your income",
        "your survival ratio is increasing, keep it up",
        "Come in again, let's go",
        "Continue to save, perhaps I'll give you special treatment",
        "yeay, another cash"
    };
    
    String[] text_set = {
        "Welcome Master, ready to deal with your allowance?",
        "I've been waiting for you, come on, there's a lot of work to be done here",
        "Master, would you like a cup of of tea?",
        "All ready, let's get started",
        "Keep it up, I got your back"
    };
    
    Random random = new Random();
    
    /**
     * Creates new form mainScreen
     */
    
    public void showDialogue(){
        miku_idle.setVisible(false);
        miku_speak.setVisible(true);
        miku_text.setVisible(true);
        mikuTextSp.setVisible(true);
        dialogue_box.setVisible(true);
    }
    
    public void hideDialogue(){
        miku_idle.setVisible(true);
        miku_speak.setVisible(false);
        miku_text.setVisible(false);
        mikuTextSp.setVisible(false);
        dialogue_box.setVisible(false);
    }
    
    public void speak(String text_to_speak){
        miku_text.setText(text_to_speak);
    }
    
    void setCurrencyValue(){
        koneksi Koneksi = new koneksi();
        
        String sql = "SELECT * FROM user_info WHERE user_id = 21092002";
        try{
            cn = Koneksi.getKoneksi();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                String getBalance = rs.getString("balance");
                recent_value.setText(getBalance);
            }
        } catch (Exception e) {
            System.out.println("Error menampilkan kurensi karena " + e.getMessage());
        }
    }
    
    void getHistory(){
        koneksi Koneksi = new koneksi();
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Income");
        model.addColumn("Paid");
        model.addColumn("Note");
        
        try{
            cn = Koneksi.getKoneksi();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM transaction");
            
            while(rs.next()){
                model.addRow(new Object[]{
                rs.getString("income"),
                rs.getString("paid"),
                rs.getString("note")
                });
            }
            historyTable.setModel(model);
        } catch (Exception e) {
            System.out.println("Error menampilkan histori transaksi karena " + e.getMessage());
        }
        historyTable.setModel(model);
    }
    
    public mainScreen() {
        initComponents();
        
        paid_button.setOpaque(false);
        paid_button.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        income_button.setOpaque(false);
        income_button.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        historyTable.setOpaque(false);
        historyTable.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        paidNotePanel.setVisible(false);
        paidNotePanel.setEnabled(false);
        incomeNotePanel.setVisible(false);
        incomeNotePanel.setEnabled(false);
        
        hideDialogue();
        
        setCurrencyValue();
        getHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incomeNotePanel = new javax.swing.JPanel();
        incomeNoteLabel = new javax.swing.JLabel();
        incomeNoteField = new javax.swing.JTextField();
        incomeOkButton = new javax.swing.JButton();
        incomeCancelButton = new javax.swing.JButton();
        paidNotePanel = new javax.swing.JPanel();
        paidNoteLabel = new javax.swing.JLabel();
        paidCancelButton = new javax.swing.JButton();
        paidNoteField = new javax.swing.JTextField();
        paidOkButton = new javax.swing.JButton();
        speakButton = new javax.swing.JButton();
        historyTablePane = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        mikuTextSp = new javax.swing.JScrollPane();
        miku_text = new javax.swing.JTextPane();
        incomeOkButton4 = new javax.swing.JButton();
        dialogue_box = new javax.swing.JLabel();
        income_button = new javax.swing.JButton();
        paid_button = new javax.swing.JButton();
        miku_speak = new javax.swing.JLabel();
        miku_idle = new javax.swing.JLabel();
        income_value = new javax.swing.JTextField();
        paid_value = new javax.swing.JTextField();
        recent_value = new javax.swing.JTextField();
        currency2 = new javax.swing.JTextField();
        currency1 = new javax.swing.JTextField();
        currency = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nobu");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        incomeNotePanel.setBackground(new java.awt.Color(102, 204, 255));
        incomeNotePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        incomeNoteLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        incomeNoteLabel.setText("Note");

        incomeNoteField.setBackground(new java.awt.Color(0, 204, 204));
        incomeNoteField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        incomeNoteField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        incomeNoteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeNoteFieldActionPerformed(evt);
            }
        });

        incomeOkButton.setBackground(new java.awt.Color(51, 153, 255));
        incomeOkButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        incomeOkButton.setText("OK");
        incomeOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeOkButtonActionPerformed(evt);
            }
        });

        incomeCancelButton.setBackground(new java.awt.Color(51, 153, 255));
        incomeCancelButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        incomeCancelButton.setText("Cancel");
        incomeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incomeNotePanelLayout = new javax.swing.GroupLayout(incomeNotePanel);
        incomeNotePanel.setLayout(incomeNotePanelLayout);
        incomeNotePanelLayout.setHorizontalGroup(
            incomeNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeNotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomeNoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeNoteField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeCancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeOkButton)
                .addContainerGap())
        );
        incomeNotePanelLayout.setVerticalGroup(
            incomeNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeNotePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(incomeNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeNoteField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeNoteLabel)
                    .addComponent(incomeOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(incomeNotePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 490, 70));

        paidNotePanel.setBackground(new java.awt.Color(102, 204, 255));
        paidNotePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        paidNoteLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        paidNoteLabel.setText("Note");

        paidCancelButton.setBackground(new java.awt.Color(51, 153, 255));
        paidCancelButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paidCancelButton.setText("Cancel");
        paidCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidCancelButtonActionPerformed(evt);
            }
        });

        paidNoteField.setBackground(new java.awt.Color(0, 204, 204));
        paidNoteField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paidNoteField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        paidNoteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidNoteFieldActionPerformed(evt);
            }
        });

        paidOkButton.setBackground(new java.awt.Color(51, 153, 255));
        paidOkButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paidOkButton.setText("OK");
        paidOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paidNotePanelLayout = new javax.swing.GroupLayout(paidNotePanel);
        paidNotePanel.setLayout(paidNotePanelLayout);
        paidNotePanelLayout.setHorizontalGroup(
            paidNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paidNotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paidNoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paidNoteField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paidCancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paidOkButton)
                .addContainerGap())
        );
        paidNotePanelLayout.setVerticalGroup(
            paidNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paidNotePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(paidNotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paidNoteField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidNoteLabel)
                    .addComponent(paidOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(paidNotePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 490, 70));

        speakButton.setBackground(new java.awt.Color(153, 255, 255));
        speakButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        speakButton.setText("Speak");
        speakButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        speakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(speakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 70, 30));

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        historyTablePane.setViewportView(historyTable);

        getContentPane().add(historyTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 480, 220));

        mikuTextSp.setBorder(null);

        miku_text.setEditable(false);
        miku_text.setBorder(null);
        miku_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miku_text.setText("What did you buy?");
        mikuTextSp.setViewportView(miku_text);

        getContentPane().add(mikuTextSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 290, 100));

        incomeOkButton4.setBackground(new java.awt.Color(204, 0, 0));
        incomeOkButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        incomeOkButton4.setText("Delete All History");
        incomeOkButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeOkButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(incomeOkButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));

        dialogue_box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainscreen/Dialog Box.png"))); // NOI18N
        getContentPane().add(dialogue_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 380, 120));

        income_button.setBackground(new java.awt.Color(153, 255, 255));
        income_button.setBorder(null);
        income_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                income_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(income_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 70));

        paid_button.setBackground(new java.awt.Color(153, 255, 255));
        paid_button.setBorder(null);
        paid_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(paid_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        miku_speak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainscreen/MikuHome.png"))); // NOI18N
        getContentPane().add(miku_speak, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        miku_idle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainscreen/MikuHome1.png"))); // NOI18N
        miku_idle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miku_idleMouseClicked(evt);
            }
        });
        getContentPane().add(miku_idle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        income_value.setBackground(new java.awt.Color(255, 255, 255));
        income_value.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        income_value.setForeground(new java.awt.Color(0, 0, 0));
        income_value.setBorder(null);
        income_value.setCaretColor(new java.awt.Color(0, 0, 0));
        income_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                income_valueActionPerformed(evt);
            }
        });
        income_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                income_valueKeyTyped(evt);
            }
        });
        getContentPane().add(income_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 360, 40));

        paid_value.setBackground(new java.awt.Color(255, 255, 255));
        paid_value.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paid_value.setForeground(new java.awt.Color(0, 0, 0));
        paid_value.setBorder(null);
        paid_value.setCaretColor(new java.awt.Color(0, 0, 0));
        paid_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_valueActionPerformed(evt);
            }
        });
        paid_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paid_valueKeyTyped(evt);
            }
        });
        getContentPane().add(paid_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 360, 40));

        recent_value.setEditable(false);
        recent_value.setBackground(new java.awt.Color(255, 255, 255));
        recent_value.setForeground(new java.awt.Color(0, 0, 0));
        recent_value.setText("0");
        recent_value.setBorder(null);
        recent_value.setCaretColor(new java.awt.Color(0, 0, 0));
        recent_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recent_valueActionPerformed(evt);
            }
        });
        getContentPane().add(recent_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 260, 30));

        currency2.setEditable(false);
        currency2.setBackground(new java.awt.Color(255, 255, 255));
        currency2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currency2.setForeground(new java.awt.Color(0, 0, 0));
        currency2.setText("Rp.");
        currency2.setBorder(null);
        currency2.setCaretColor(new java.awt.Color(0, 0, 0));
        currency2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currency2ActionPerformed(evt);
            }
        });
        getContentPane().add(currency2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 30, 40));

        currency1.setEditable(false);
        currency1.setBackground(new java.awt.Color(255, 255, 255));
        currency1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currency1.setForeground(new java.awt.Color(0, 0, 0));
        currency1.setText("Rp.");
        currency1.setBorder(null);
        currency1.setCaretColor(new java.awt.Color(0, 0, 0));
        currency1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currency1ActionPerformed(evt);
            }
        });
        getContentPane().add(currency1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 30, 40));

        currency.setEditable(false);
        currency.setBackground(new java.awt.Color(255, 255, 255));
        currency.setForeground(new java.awt.Color(0, 0, 0));
        currency.setText("Rp.");
        currency.setBorder(null);
        currency.setCaretColor(new java.awt.Color(0, 0, 0));
        currency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyActionPerformed(evt);
            }
        });
        getContentPane().add(currency, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 280, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainscreen/Home Screen.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void currencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyActionPerformed

    private void currency1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currency1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currency1ActionPerformed

    private void paid_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_buttonActionPerformed
        // TODO add your handling code here:
        if(paid_value.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Please fill the blank");
            paid_value.requestFocus();
        }
        int paidValueInt = Integer.parseInt(paid_value.getText());
        int recentValueInt = Integer.parseInt(recent_value.getText());
        if(recentValueInt - paidValueInt > 0){
            paidNotePanel.setVisible(true);
            paidNotePanel.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Balance must not be Rp.0");
            paid_value.requestFocus();
        }
    }//GEN-LAST:event_paid_buttonActionPerformed

    private void paid_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paid_valueActionPerformed

    private void income_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_income_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_income_valueActionPerformed

    private void income_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_income_buttonActionPerformed
        // TODO add your handling code here:
        
        if(income_value.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Please fill the blank");
            income_value.requestFocus();;
        } else {
            incomeNotePanel.setVisible(true);
            incomeNotePanel.setEnabled(true);
        }
    }//GEN-LAST:event_income_buttonActionPerformed

    private void paid_valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paid_valueKeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_paid_valueKeyTyped

    private void income_valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_income_valueKeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar()))){
            evt.consume();
        }    
    }//GEN-LAST:event_income_valueKeyTyped

    private void currency2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currency2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currency2ActionPerformed

    private void recent_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recent_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recent_valueActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/mainscreen/miku.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void paidNoteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidNoteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidNoteFieldActionPerformed

    private void incomeNoteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeNoteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeNoteFieldActionPerformed

    private void paidOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidOkButtonActionPerformed
        // TODO add your handling code here:
        int rand_number = random.nextInt(5);
        speak(paid_text_set[rand_number]);
        showDialogue();
        JOptionPane.showMessageDialog(null, "Your balance decreased " + "Rp." + paid_value.getText());
        
        try {
            Thread.sleep(2000);
            hideDialogue();
        } catch (InterruptedException e){
        
        }
        
        koneksi Koneksi = new koneksi();
        String paidInput = paid_value.getText();
        String paidNoteInput = paidNoteField.getText();
        String sql = "INSERT INTO transaction (paid, note) VALUES (" + paidInput + ", '" + paidNoteInput + "')";
        String updateSql = "UPDATE user_info set balance = " + recent_value.getText() + "-" + paidInput;

        try {
            cn = Koneksi.getKoneksi();
            st.execute(sql);
            st.execute(updateSql);
            paid_value.setText("");
            paidNoteLabel.setText("");
            getHistory();  
            setCurrencyValue();
        } catch (Exception e) {
            System.out.println("Error mengambil data : " + e.getMessage());
            System.out.println(sql);
            System.out.println(updateSql);
        }
        
        paidNotePanel.setVisible(false);
        paidNotePanel.setEnabled(false);
    }//GEN-LAST:event_paidOkButtonActionPerformed

    private void paidCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidCancelButtonActionPerformed
        // TODO add your handling code here:
        paidNotePanel.setVisible(false);
        paidNotePanel.setEnabled(false);
    }//GEN-LAST:event_paidCancelButtonActionPerformed

    private void incomeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeCancelButtonActionPerformed
        // TODO add your handling code here:
        incomeNotePanel.setVisible(false);
        incomeNotePanel.setEnabled(false);
    }//GEN-LAST:event_incomeCancelButtonActionPerformed

    private void incomeOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeOkButtonActionPerformed
        // TODO add your handling code here:
        int rand_number = random.nextInt(5);
        speak(income_text_set[rand_number]);
        showDialogue();
        JOptionPane.showMessageDialog(null, "Your balance increased " + "Rp." + income_value.getText());
        
        try {
            Thread.sleep(2000);
            hideDialogue();
        } catch (InterruptedException e){
        
        }
        
        koneksi Koneksi = new koneksi();
        String incomeInput = income_value.getText();
        String incomeNoteInput = incomeNoteField.getText();
        String sql = "INSERT INTO transaction (income, note) VALUES (" + incomeInput + ", '" + incomeNoteInput + "')";
        String updateSql = "UPDATE user_info set balance = " + recent_value.getText() + "+" + incomeInput;

        try {
            cn = Koneksi.getKoneksi();
            st.execute(sql);
            st.execute(updateSql);
            income_value.setText("");
            incomeNoteLabel.setText("");
            getHistory();  
            setCurrencyValue();
        } catch (Exception e) {
            System.out.println("Error menambahkan data : " + e.getMessage());
            System.out.println(sql);
            System.out.println(updateSql);
        }
        
        incomeNotePanel.setVisible(false);
        incomeNotePanel.setEnabled(false);
    }//GEN-LAST:event_incomeOkButtonActionPerformed

    private void incomeOkButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeOkButton4ActionPerformed
        // TODO add your handling code here:
        koneksi Koneksi = new koneksi();
        String sql = "DELETE FROM transaction";
        int confirm = JOptionPane.showConfirmDialog(null, "All history will be deleted\nProceed?", "Delete All", JOptionPane.YES_NO_OPTION);
        if(confirm == 0){
            try{
                cn = Koneksi.getKoneksi();
                st.execute(sql);
                JOptionPane.showMessageDialog(null, "All data has been deleted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Delete failure");
                System.out.println("Gagal menghapus seluruh data karena " + e.getMessage());
                System.out.println(sql);
            }
        }
        getHistory();
    }//GEN-LAST:event_incomeOkButton4ActionPerformed

    private void miku_idleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miku_idleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miku_idleMouseClicked

    private void speakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakButtonActionPerformed
        // TODO add your handling code here:
        
        int rand_number = random.nextInt(5);
        speak(text_set[rand_number]);
        showDialogue();
        JOptionPane.showMessageDialog(null, "Miku Speak");
        
        try {
            Thread.sleep(2000);
            hideDialogue();
        } catch (InterruptedException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_speakButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField currency;
    private javax.swing.JTextField currency1;
    private javax.swing.JTextField currency2;
    private javax.swing.JLabel dialogue_box;
    private javax.swing.JTable historyTable;
    private javax.swing.JScrollPane historyTablePane;
    private javax.swing.JButton incomeCancelButton;
    private javax.swing.JTextField incomeNoteField;
    private javax.swing.JLabel incomeNoteLabel;
    private javax.swing.JPanel incomeNotePanel;
    private javax.swing.JButton incomeOkButton;
    private javax.swing.JButton incomeOkButton4;
    private javax.swing.JButton income_button;
    private javax.swing.JTextField income_value;
    private javax.swing.JScrollPane mikuTextSp;
    private javax.swing.JLabel miku_idle;
    private javax.swing.JLabel miku_speak;
    private javax.swing.JTextPane miku_text;
    private javax.swing.JButton paidCancelButton;
    private javax.swing.JTextField paidNoteField;
    private javax.swing.JLabel paidNoteLabel;
    private javax.swing.JPanel paidNotePanel;
    private javax.swing.JButton paidOkButton;
    private javax.swing.JButton paid_button;
    private javax.swing.JTextField paid_value;
    private javax.swing.JTextField recent_value;
    private javax.swing.JButton speakButton;
    // End of variables declaration//GEN-END:variables
}
